services:

    orthanc-s3-default:
        image: orthancteam/orthanc-pre-release:master-unstable
        ports: [8052:8042]
        depends_on:
            - toxiproxy-s3
            - toxiproxy-pg-s3
        # volumes:
        #     - orthanc-s3-default-sqlite-storage:/var/lib/orthanc/db
        environment:
            ORTHANC_JSON: |
                {
                    "Name": "ORTHANC S3 default",
                    "AuthenticationEnabled": false,
                    "DicomServerEnabled": false,
                    "StableAge": 5,
                    "AwsS3Storage": {
                        "BucketName": "default-bucket",
                        "Region": "eu-west-1",
                        "AccessKey": "s3-like-admin",
                        "SecretKey": "change-me",
                        "Endpoint": "http://toxiproxy-s3:8333",
                        "VirtualAddressing": false
                    },
                    "PostgreSQL" : {
                        "Host": "toxiproxy-pg-s3"
                    }
                }
            VERBOSE_ENABLED: "true"
            VERBOSE_STARTUP: "true"

    orthanc-s3-zip:
        build: .
        # image: orthancteam/orthanc-pre-release:master-unstable
        ports: [8053:8042]
        depends_on:
            - toxiproxy-s3
            - toxiproxy-pg-default
        volumes:
            # - orthanc-s3-zip-sqlite-storage:/var/lib/orthanc/db
            - ./tmp-local-storage/:/tmp-local-storage
            - ./plugin:/plugin
        environment:
            ORTHANC_JSON: |
                {
                    "Name": "ORTHANC S3 zip",
                    "AuthenticationEnabled": false,
                    "DicomServerEnabled": false,
                    "PythonScript": "/plugin/plugin.py",
                    "StableAge": 5,
                    "S3Zip": {
                        "LocalTemporaryFolder": "/tmp-local-storage",
                        "BucketName": "zip-bucket",
                        "Region": "eu-west-1",
                        "AccessKey": "s3-like-admin ",
                        "SecretKey": "change-me",
                        "Endpoint": "http://toxiproxy-s3:8333",
                        "VirtualAddressing": false,
                        "EnableCompression": false,
                        "LocalStorageMaxSizeMB": 3000,
                        "PrefixKey": "orthanc-zips",
                        "S3HousekeeperIntervalSeconds": 5
                    },
                    "Python": {
                        "AllowThreads": true
                    },
                    "OrthancExplorer2": {
                        "UiOptions": {
                            "EnableApiViewMenu": true
                        }
                    },
                    "PostgreSQL" : {
                        "Host": "toxiproxy-pg-default"
                    }
                }
            VERBOSE_ENABLED: "true"
            VERBOSE_STARTUP: "true"
            S3ZIP_LOG_LEVEL: "INFO"

    s3-like:
        image: chrislusf/seaweedfs
        # don't expose these ports in a real world setup
        ports: [8333:8333]
        environment:
            - AWS_ACCESS_KEY_ID=s3-like-admin
            - AWS_SECRET_ACCESS_KEY=change-me
            - S3_BUCKET=zip-bucket
        volumes:
            - s3-like-storage:/data
        command: mini -dir=/data

    toxiproxy-s3:
        depends_on: 
            - s3-like
        ports: ["18333:8333"]
        image: ghcr.io/shopify/toxiproxy

    toxiproxy-pg-s3:
        depends_on: 
            - pg-s3
        ports: ["15432:5432"]
        image: ghcr.io/shopify/toxiproxy

    toxiproxy-pg-default:
        depends_on: 
            - pg-default
        ports: ["25432:5432"]
        image: ghcr.io/shopify/toxiproxy

    toxiproxy-config:
        image: curlimages/curl
        depends_on: 
            - toxiproxy-s3
            - toxiproxy-pg-s3
            - toxiproxy-pg-default
        restart: on-failure
        entrypoint: >
            sh -c "sleep 3;
            curl -sf -X POST http://toxiproxy-s3:8474/proxies -H 'Content-Type: application/json' -d '{\"name\":\"s3-like\",\"listen\":\"0.0.0.0:8333\",\"upstream\":\"s3-like:8333\"}';
            curl -sf -X POST http://toxiproxy-s3:8474/proxies/s3-like/toxics -H 'Content-Type: application/json' -d '{\"type\":\"latency\",\"attributes\":{\"latency\":50,\"jitter\":0}}';
            curl -sf -X POST http://toxiproxy-pg-s3:8474/proxies -H 'Content-Type: application/json' -d '{\"name\":\"pg-s3\",\"listen\":\"0.0.0.0:5432\",\"upstream\":\"pg-s3:5432\"}';
            curl -sf -X POST http://toxiproxy-pg-s3:8474/proxies/pg-s3/toxics -H 'Content-Type: application/json' -d '{\"type\":\"latency\",\"attributes\":{\"latency\":10,\"jitter\":0}}';
            curl -sf -X POST http://toxiproxy-pg-default:8474/proxies -H 'Content-Type: application/json' -d '{\"name\":\"pg-default\",\"listen\":\"0.0.0.0:5432\",\"upstream\":\"pg-default:5432\"}';
            curl -sf -X POST http://toxiproxy-pg-default:8474/proxies/pg-default/toxics -H 'Content-Type: application/json' -d '{\"type\":\"latency\",\"attributes\":{\"latency\":10,\"jitter\":0}}';"


    pg-s3:
        image: postgres:18
        restart: unless-stopped
        # ports: ["5432:5432"]
        volumes: ["orthanc-s3-db:/var/lib/postgresql/18/docker"]
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"

    pg-default:
        image: postgres:18
        restart: unless-stopped
        # ports: ["5432:5432"]
        volumes: ["orthanc-default-db:/var/lib/postgresql/18/docker"]
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
    s3-like-storage:
    orthanc-default-db:
    orthanc-s3-db:
