#!/usr/bin/env bash

function usage {
	cat <<-EOF >&2
	Usage: $(basename "$0") [-h] CREDENTIALS_FILE VOLUME_NAME

	KEY_FILE is the GCP service account credentials file.
	VOLUME_NAME is the Docker volume name.
	EOF
}

while getopts h opt; do
	case $opt in
	h) usage && exit;;
	?) usage && exit 1;;
	esac
done
shift $((OPTIND-1))
if (($# != 2)); then
	usage
	exit 1
fi
credentials=$1
volume=$2

echo "Writing credentials file \"$credentials\" in volume \"$volume\"" >&2
if ! docker run --rm "--volume=$volume:/mnt" --interactive \
		alpine dd "of=/mnt/gcp-credentials" <"$credentials"
then
	echo "Could not write certificate" >&2
	exit 2
fi
