FROM osimis/orthanc:buster-211115

RUN apt-get update
RUN apt-get --assume-yes install curl gnupg2

RUN mkdir /downloads

RUN curl https://packages.microsoft.com/keys/microsoft.asc > /downloads/microsoft.asc
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-key add /downloads/microsoft.asc
RUN apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install gdcm and dcmtk that are used in a Lua scripts
RUN apt-get --assume-yes update
RUN	DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install dcmtk libgdcm-tools 
RUN	DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install odbc-postgresql

COPY orthanc.json /etc/orthanc/orthanc.json
COPY odbc.ini /etc/
