services:

  orthanc:
    image: orthancteam/orthanc
    ports: ["8042:8042"]
    volumes: 
      - "orthanc-storage:/var/lib/orthanc/db"
      - ./custom.css:/custom.css
      - ./orthanc.team.png:/orthanc.team.png
    restart: unless-stopped
    environment:
      ORTHANC_JSON: |
        {
          "AuthenticationEnabled": false,
          "Name": "Custom OE2",

          "OrthancExplorer2": {
            "IsDefaultOrthancUI": true,
            "Theme": "dark",
            "CustomLogoPath": "/orthanc.team.png",
            "CustomCssPath": "/custom.css"
          }
        }


volumes:
  orthanc-storage:
