services:

    orthanc:
        image: orthancteam/orthanc
        ports: [8042:8042]
        environment:
            - ORTHANC__NAME=ORTHANC S3 like demo
            - ORTHANC__AWS_S3_STORAGE__BUCKET_NAME=my-sample-bucket
            - ORTHANC__AWS_S3_STORAGE__REGION=eu-west-1
            - ORTHANC__AWS_S3_STORAGE__ACCESS_KEY=s3-like-admin
            - ORTHANC__AWS_S3_STORAGE__SECRET_KEY=change-me
            - ORTHANC__AWS_S3_STORAGE__ENDPOINT=http://s3-like:8333
            - ORTHANC__AWS_S3_STORAGE__VIRTUAL_ADDRESSING=false
            # - ORTHANC__AWS_S3_STORAGE__HYBRID_MODE=WriteToObjectStorage
            # - ORTHANC__AWS_S3_STORAGE__HYBRID_MODE=WriteToFileSystem
            - ORTHANC__AUTHENTICATION_ENABLED=false
            - ORTHANC__DICOM_SERVER_ENABLED=false
            - VERBOSE_ENABLED=true
            - VERBOSE_STARTUP=true
        volumes:
            - orthanc-sqlite-storage:/var/lib/orthanc/db

    s3-like:
        image: chrislusf/seaweedfs
        # don't expose these ports in a real world setup
        ports: [8333:8333, 8888:8888]
        environment:
            - AWS_ACCESS_KEY_ID=s3-like-admin
            - AWS_SECRET_ACCESS_KEY=change-me
            - S3_BUCKET=my-sample-bucket
        volumes:
            - s3-like-storage:/data
        command: mini -dir=/data


volumes:
    s3-like-storage:
    orthanc-sqlite-storage:

networks:
    test: