services:

  orthanc-a-server:
    build: nginx-a
    depends_on: [orthanc-a]
    restart: unless-stopped
    ports: ["443:443"]
    volumes: ["./tls:/etc/nginx/tls"]
  orthanc-a:
    build: orthanc-a
    restart: unless-stopped
    volumes:
      - "orthanc-a-storage:/var/lib/orthanc/db"
      - "./tls:/etc/share/orthanc/tls"
  orthanc-b-server:
    build: nginx-b
    depends_on: [orthanc-b]
    restart: unless-stopped
    ports: ["843:443"]
    volumes: ["./tls:/etc/nginx/tls"]
  orthanc-b:
    build: orthanc-b
    restart: unless-stopped
    volumes:
      - "orthanc-b-storage:/var/lib/orthanc/db"
      - "./tls:/etc/share/orthanc/tls"
  orthanc-b-forward-proxy:
    build: forward-proxy
    restart: unless-stopped
    volumes:
      - "./tls:/usr/tls"
  external-web-service:
    build: external-web-service
    restart: unless-stopped
    volumes:
      - "./tls:/usr/tls"

volumes:

  orthanc-a-storage:
  orthanc-b-storage:
