services:

  orthanc:
    image: orthancteam/orthanc:25.8.0
    ports: ["8042:8042", "4242:4242"]
    volumes:
      - orthanc-storage:/var/lib/orthanc/db/
      - ./plugin.py:/scripts/plugin.py
    environment:
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC_JSON: |
        {
          "Name": "C-Move filtering demo",
          "AuthenticationEnabled": false,
          "PythonScript": "/scripts/plugin.py",
          "DicomModalities": {
            "modality": ["MODALITY", "modality", 4242]
          }
        }

  modality:
    image: orthancteam/orthanc:25.8.0
    ports: ["8043:8042"]
    volumes:
      - modality-storage:/var/lib/orthanc/db/
    depends_on:
      - orthanc
    environment:
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC_JSON: |
        {
          "RejectedSopClasses" : [
            "1.2.840.10008.5.1.4.1.1.104.1"
          ],
          "Name": "Modality",
          "DicomAet": "MODALITY",
          "AuthenticationEnabled": false,
          "DicomModalities": {
            "orthanc": ["ORTHANC", "orthanc", 4242]
          }
        }


volumes:
  orthanc-storage:
  modality-storage:
