services:
  orthanc-under-tests:
    build: 
      context: orthanc-under-tests
      dockerfile: Dockerfile.mssql
    depends_on:
      - sql-server
    environment:
      ORTHANC__ODBC__INDEX_CONNECTION_STRING: "DSN=mssql17;Uid=sa;Pwd=MyStrOngPa55word!"
      ORTHANC__ODBC__STORAGE_CONNECTION_STRING: "DSN=mssql17;Uid=sa;Pwd=MyStrOngPa55word!"
      ORTHANC__ODBC__ENABLE_INDEX: "true"
      ORTHANC__ODBC__ENABLE_STORAGE: "true"
      VERBOSE_STARTUP: "true"
      VERBOSE_ENABLED: "false"

  orthanc-tests:
    build: orthanc-tests
    depends_on:
      - orthanc-under-tests

  sql-server:
    build: sql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyStrOngPa55word!"
