services:

  orthanc-under-tests:
    build: orthanc-under-tests
    depends_on:
      - odbc-mysql-server
    environment:
      ORTHANC__ODBC__INDEX_CONNECTION_STRING: "DSN=mysql8"
      ORTHANC__ODBC__STORAGE_CONNECTION_STRING: "DSN=mysql8"
      ORTHANC__ODBC__ENABLE_INDEX: "true"
      ORTHANC__ODBC__ENABLE_STORAGE: "true"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"

  orthanc-tests:
    build: orthanc-tests
    depends_on:
      - orthanc-under-tests

  odbc-mysql-server:
    image: mysql:8.0
    command:
      [
        mysqld,
        --default-authentication-plugin=mysql_native_password,
        --log-bin-trust-function-creators=1,
      ]
    environment:
      MYSQL_PASSWORD: foo
      MYSQL_USER: test-user
      MYSQL_DATABASE: orthanc
      MYSQL_ROOT_PASSWORD: foo-root
