services:

  orthanc:
    image: orthancteam/orthanc-pre-release:advanced-storage-20241002
    ports: ["8044:8042"]
    volumes: 
      - orthanc-storage-1:/orthanc-storage-1
      - orthanc-storage-2:/orthanc-storage-2
    depends_on:
      - orthanc-index
    environment:
      ORTHANC__NAME: "orthanc"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"

      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ADVANCED_STORAGE_PLUGIN_ENABLED: "true"

      ORTHANC_JSON: |
        {
          "Name": "Orthanc demo",
          "AuthenticationEnabled": false,
          "PostgreSQL" : {
            "Host": "orthanc-index",
            "TransactionMode": "ReadCommitted"
          },
          "AdvancedStorage": {
            "Enable": true,
            
            //"NamingScheme": "dicom/{split(StudyDate)}/{StudyInstanceUID} - {PatientID}/{SeriesInstanceUID}/{pad6(InstanceNumber)} - {UUID}{.ext}",
            "NamingScheme": "dicom/{PatientID} - {PatientName}/{StudyDate} - {StudyInstanceUID} - {StudyDescription}/{SeriesInstanceUID}/{UUID}{.ext}",
            "MaxPathLength": 500,

            "OtherAttachmentsPrefix": "attachments/",

            "MultipleStorages" : {
              "Storages" : {
                "1" : "/orthanc-storage-1",
                "2" : "/orthanc-storage-2"
              },

              // the storage on which new data is stored.
              // There's currently no automatic changes of disks
              "CurrentStorage" : "1"
            }
          }
        }

  orthanc-index:
    image: postgres:15
    restart: unless-stopped
    ports: ["5432:5432"]
    volumes: ["orthanc-index:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


volumes:
  orthanc-storage-1:
  orthanc-storage-2:
  orthanc-index:
