services:

  orthanc-1:
    image: orthancteam/orthanc:25.6.4
    ports: ["8044:8042"]
    volumes: 
      - orthanc-storage-1:/orthanc-storage-1
      - orthanc-storage-2:/orthanc-storage-2
      - ./orthanc.json:/etc/orthanc/orthanc.json
      - ./folder-to-index/:/folder-to-index/
    depends_on:
      - orthanc-index
    environment:
      ORTHANC__NAME: "orthanc-1"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"

      # STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      # OHIF_PLUGIN_ENABLED: "true"
      # DICOM_WEB_PLUGIN_ENABLED: "true"
      ADVANCED_STORAGE_PLUGIN_ENABLED: "true"


  orthanc-2:
    image: orthancteam/orthanc:25.6.4
    ports: ["8045:8042"]
    volumes: 
      - orthanc-storage-1:/orthanc-storage-1
      - orthanc-storage-2:/orthanc-storage-2
      - ./orthanc.json:/etc/orthanc/orthanc.json
      - ./folder-to-index/:/folder-to-index/

    depends_on:
      - orthanc-index
    environment:
      ORTHANC__NAME: "orthanc-2"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"

      # STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      # OHIF_PLUGIN_ENABLED: "true"
      # DICOM_WEB_PLUGIN_ENABLED: "true"
      ADVANCED_STORAGE_PLUGIN_ENABLED: "true"

  orthanc-index:
    image: postgres:15
    restart: unless-stopped
    ports: ["5432:5432"]
    volumes: ["orthanc-index:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


volumes:
  orthanc-storage-1:
  orthanc-storage-2:
  orthanc-index:
